name: AppServiceVNetIntegration
summary: VNet Integration of an App Service
description: Deploys an App Service inside a VNet and the associated private endpoint
runner: https://dockerhub.io/aichehda/deployment-environments-runners-terraform:1.9.3
templatePath: provider.tf

parameters:
- id: "vnet_address_prefix"
  name: "VNet Address Prefix (Optional)"
  description: "VNet Address Prefix to set to the VNet which contains the resources"
  type: "string"
  default: "10.0"
